#nullable disable

namespace GPUVulkan
{
	public enum StdVideoH264ChromaFormatIdc
	{
		STD_VIDEO_H264_CHROMA_FORMAT_IDC_MONOCHROME = 0,
		STD_VIDEO_H264_CHROMA_FORMAT_IDC_420 = 1,
		STD_VIDEO_H264_CHROMA_FORMAT_IDC_422 = 2,
		STD_VIDEO_H264_CHROMA_FORMAT_IDC_444 = 3,
		STD_VIDEO_H264_CHROMA_FORMAT_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264ProfileIdc
	{
		STD_VIDEO_H264_PROFILE_IDC_BASELINE = 66,
		STD_VIDEO_H264_PROFILE_IDC_MAIN = 77,
		STD_VIDEO_H264_PROFILE_IDC_HIGH = 100,
		STD_VIDEO_H264_PROFILE_IDC_HIGH_444_PREDICTIVE = 244,
		STD_VIDEO_H264_PROFILE_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264LevelIdc
	{
		STD_VIDEO_H264_LEVEL_IDC_1_0 = 0,
		STD_VIDEO_H264_LEVEL_IDC_1_1 = 1,
		STD_VIDEO_H264_LEVEL_IDC_1_2 = 2,
		STD_VIDEO_H264_LEVEL_IDC_1_3 = 3,
		STD_VIDEO_H264_LEVEL_IDC_2_0 = 4,
		STD_VIDEO_H264_LEVEL_IDC_2_1 = 5,
		STD_VIDEO_H264_LEVEL_IDC_2_2 = 6,
		STD_VIDEO_H264_LEVEL_IDC_3_0 = 7,
		STD_VIDEO_H264_LEVEL_IDC_3_1 = 8,
		STD_VIDEO_H264_LEVEL_IDC_3_2 = 9,
		STD_VIDEO_H264_LEVEL_IDC_4_0 = 10,
		STD_VIDEO_H264_LEVEL_IDC_4_1 = 11,
		STD_VIDEO_H264_LEVEL_IDC_4_2 = 12,
		STD_VIDEO_H264_LEVEL_IDC_5_0 = 13,
		STD_VIDEO_H264_LEVEL_IDC_5_1 = 14,
		STD_VIDEO_H264_LEVEL_IDC_5_2 = 15,
		STD_VIDEO_H264_LEVEL_IDC_6_0 = 16,
		STD_VIDEO_H264_LEVEL_IDC_6_1 = 17,
		STD_VIDEO_H264_LEVEL_IDC_6_2 = 18,
		STD_VIDEO_H264_LEVEL_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264PocType
	{
		STD_VIDEO_H264_POC_TYPE_0 = 0,
		STD_VIDEO_H264_POC_TYPE_1 = 1,
		STD_VIDEO_H264_POC_TYPE_2 = 2,
		STD_VIDEO_H264_POC_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264AspectRatioIdc
	{
		STD_VIDEO_H264_ASPECT_RATIO_IDC_UNSPECIFIED = 0,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_SQUARE = 1,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_12_11 = 2,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_10_11 = 3,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_16_11 = 4,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_40_33 = 5,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_24_11 = 6,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_20_11 = 7,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_32_11 = 8,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_80_33 = 9,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_18_11 = 10,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_15_11 = 11,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_64_33 = 12,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_160_99 = 13,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_4_3 = 14,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_3_2 = 15,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_2_1 = 16,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_EXTENDED_SAR = 255,
		STD_VIDEO_H264_ASPECT_RATIO_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264WeightedBipredIdc
	{
		STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_DEFAULT = 0,
		STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_EXPLICIT = 1,
		STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_IMPLICIT = 2,
		STD_VIDEO_H264_WEIGHTED_BIPRED_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264ModificationOfPicNumsIdc
	{
		STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_SHORT_TERM_SUBTRACT = 0,
		STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_SHORT_TERM_ADD = 1,
		STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_LONG_TERM = 2,
		STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_END = 3,
		STD_VIDEO_H264_MODIFICATION_OF_PIC_NUMS_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264MemMgmtControlOp
	{
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_END = 0,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_SHORT_TERM = 1,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_LONG_TERM = 2,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_MARK_LONG_TERM = 3,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_SET_MAX_LONG_TERM_INDEX = 4,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_UNMARK_ALL = 5,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_MARK_CURRENT_AS_LONG_TERM = 6,
		STD_VIDEO_H264_MEM_MGMT_CONTROL_OP_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264CabacInitIdc
	{
		STD_VIDEO_H264_CABAC_INIT_IDC_0 = 0,
		STD_VIDEO_H264_CABAC_INIT_IDC_1 = 1,
		STD_VIDEO_H264_CABAC_INIT_IDC_2 = 2,
		STD_VIDEO_H264_CABAC_INIT_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264DisableDeblockingFilterIdc
	{
		STD_VIDEO_H264_DISABLE_DEBLOCKING_FILTER_IDC_DISABLED = 0,
		STD_VIDEO_H264_DISABLE_DEBLOCKING_FILTER_IDC_ENABLED = 1,
		STD_VIDEO_H264_DISABLE_DEBLOCKING_FILTER_IDC_PARTIAL = 2,
		STD_VIDEO_H264_DISABLE_DEBLOCKING_FILTER_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264SliceType
	{
		STD_VIDEO_H264_SLICE_TYPE_P = 0,
		STD_VIDEO_H264_SLICE_TYPE_B = 1,
		STD_VIDEO_H264_SLICE_TYPE_I = 2,
		STD_VIDEO_H264_SLICE_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264PictureType
	{
		STD_VIDEO_H264_PICTURE_TYPE_P = 0,
		STD_VIDEO_H264_PICTURE_TYPE_B = 1,
		STD_VIDEO_H264_PICTURE_TYPE_I = 2,
		STD_VIDEO_H264_PICTURE_TYPE_IDR = 5,
		STD_VIDEO_H264_PICTURE_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH264NonVclNaluType
	{
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_SPS = 0,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_PPS = 1,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_AUD = 2,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_PREFIX = 3,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_END_OF_SEQUENCE = 4,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_END_OF_STREAM = 5,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_PRECODED = 6,
		STD_VIDEO_H264_NON_VCL_NALU_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoDecodeH264FieldOrderCount
	{
		STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_TOP = 0,
		STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_BOTTOM = 1,
		STD_VIDEO_DECODE_H264_FIELD_ORDER_COUNT_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265ChromaFormatIdc
	{
		STD_VIDEO_H265_CHROMA_FORMAT_IDC_MONOCHROME = 0,
		STD_VIDEO_H265_CHROMA_FORMAT_IDC_420 = 1,
		STD_VIDEO_H265_CHROMA_FORMAT_IDC_422 = 2,
		STD_VIDEO_H265_CHROMA_FORMAT_IDC_444 = 3,
		STD_VIDEO_H265_CHROMA_FORMAT_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265ProfileIdc
	{
		STD_VIDEO_H265_PROFILE_IDC_MAIN = 1,
		STD_VIDEO_H265_PROFILE_IDC_MAIN_10 = 2,
		STD_VIDEO_H265_PROFILE_IDC_MAIN_STILL_PICTURE = 3,
		STD_VIDEO_H265_PROFILE_IDC_FORMAT_RANGE_EXTENSIONS = 4,
		STD_VIDEO_H265_PROFILE_IDC_SCC_EXTENSIONS = 9,
		STD_VIDEO_H265_PROFILE_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265LevelIdc
	{
		STD_VIDEO_H265_LEVEL_IDC_1_0 = 0,
		STD_VIDEO_H265_LEVEL_IDC_2_0 = 1,
		STD_VIDEO_H265_LEVEL_IDC_2_1 = 2,
		STD_VIDEO_H265_LEVEL_IDC_3_0 = 3,
		STD_VIDEO_H265_LEVEL_IDC_3_1 = 4,
		STD_VIDEO_H265_LEVEL_IDC_4_0 = 5,
		STD_VIDEO_H265_LEVEL_IDC_4_1 = 6,
		STD_VIDEO_H265_LEVEL_IDC_5_0 = 7,
		STD_VIDEO_H265_LEVEL_IDC_5_1 = 8,
		STD_VIDEO_H265_LEVEL_IDC_5_2 = 9,
		STD_VIDEO_H265_LEVEL_IDC_6_0 = 10,
		STD_VIDEO_H265_LEVEL_IDC_6_1 = 11,
		STD_VIDEO_H265_LEVEL_IDC_6_2 = 12,
		STD_VIDEO_H265_LEVEL_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265SliceType
	{
		STD_VIDEO_H265_SLICE_TYPE_B = 0,
		STD_VIDEO_H265_SLICE_TYPE_P = 1,
		STD_VIDEO_H265_SLICE_TYPE_I = 2,
		STD_VIDEO_H265_SLICE_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265PictureType
	{
		STD_VIDEO_H265_PICTURE_TYPE_P = 0,
		STD_VIDEO_H265_PICTURE_TYPE_B = 1,
		STD_VIDEO_H265_PICTURE_TYPE_I = 2,
		STD_VIDEO_H265_PICTURE_TYPE_IDR = 3,
		STD_VIDEO_H265_PICTURE_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoH265AspectRatioIdc
	{
		STD_VIDEO_H265_ASPECT_RATIO_IDC_UNSPECIFIED = 0,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_SQUARE = 1,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_12_11 = 2,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_10_11 = 3,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_16_11 = 4,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_40_33 = 5,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_24_11 = 6,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_20_11 = 7,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_32_11 = 8,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_80_33 = 9,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_18_11 = 10,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_15_11 = 11,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_64_33 = 12,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_160_99 = 13,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_4_3 = 14,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_3_2 = 15,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_2_1 = 16,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_EXTENDED_SAR = 255,
		STD_VIDEO_H265_ASPECT_RATIO_IDC_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9Profile
	{
		STD_VIDEO_VP9_PROFILE_0 = 0,
		STD_VIDEO_VP9_PROFILE_1 = 1,
		STD_VIDEO_VP9_PROFILE_2 = 2,
		STD_VIDEO_VP9_PROFILE_3 = 3,
		STD_VIDEO_VP9_PROFILE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9Level
	{
		STD_VIDEO_VP9_LEVEL_1_0 = 0,
		STD_VIDEO_VP9_LEVEL_1_1 = 1,
		STD_VIDEO_VP9_LEVEL_2_0 = 2,
		STD_VIDEO_VP9_LEVEL_2_1 = 3,
		STD_VIDEO_VP9_LEVEL_3_0 = 4,
		STD_VIDEO_VP9_LEVEL_3_1 = 5,
		STD_VIDEO_VP9_LEVEL_4_0 = 6,
		STD_VIDEO_VP9_LEVEL_4_1 = 7,
		STD_VIDEO_VP9_LEVEL_5_0 = 8,
		STD_VIDEO_VP9_LEVEL_5_1 = 9,
		STD_VIDEO_VP9_LEVEL_5_2 = 10,
		STD_VIDEO_VP9_LEVEL_6_0 = 11,
		STD_VIDEO_VP9_LEVEL_6_1 = 12,
		STD_VIDEO_VP9_LEVEL_6_2 = 13,
		STD_VIDEO_VP9_LEVEL_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9FrameType
	{
		STD_VIDEO_VP9_FRAME_TYPE_KEY = 0,
		STD_VIDEO_VP9_FRAME_TYPE_NON_KEY = 1,
		STD_VIDEO_VP9_FRAME_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9ReferenceName
	{
		STD_VIDEO_VP9_REFERENCE_NAME_INTRA_FRAME = 0,
		STD_VIDEO_VP9_REFERENCE_NAME_LAST_FRAME = 1,
		STD_VIDEO_VP9_REFERENCE_NAME_GOLDEN_FRAME = 2,
		STD_VIDEO_VP9_REFERENCE_NAME_ALTREF_FRAME = 3,
		STD_VIDEO_VP9_REFERENCE_NAME_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9InterpolationFilter
	{
		STD_VIDEO_VP9_INTERPOLATION_FILTER_EIGHTTAP = 0,
		STD_VIDEO_VP9_INTERPOLATION_FILTER_EIGHTTAP_SMOOTH = 1,
		STD_VIDEO_VP9_INTERPOLATION_FILTER_EIGHTTAP_SHARP = 2,
		STD_VIDEO_VP9_INTERPOLATION_FILTER_BILINEAR = 3,
		STD_VIDEO_VP9_INTERPOLATION_FILTER_SWITCHABLE = 4,
		STD_VIDEO_VP9_INTERPOLATION_FILTER_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoVP9ColorSpace
	{
		STD_VIDEO_VP9_COLOR_SPACE_UNKNOWN = 0,
		STD_VIDEO_VP9_COLOR_SPACE_BT_601 = 1,
		STD_VIDEO_VP9_COLOR_SPACE_BT_709 = 2,
		STD_VIDEO_VP9_COLOR_SPACE_SMPTE_170 = 3,
		STD_VIDEO_VP9_COLOR_SPACE_SMPTE_240 = 4,
		STD_VIDEO_VP9_COLOR_SPACE_BT_2020 = 5,
		STD_VIDEO_VP9_COLOR_SPACE_RESERVED = 6,
		STD_VIDEO_VP9_COLOR_SPACE_RGB = 7,
		STD_VIDEO_VP9_COLOR_SPACE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1Profile
	{
		STD_VIDEO_AV1_PROFILE_MAIN = 0,
		STD_VIDEO_AV1_PROFILE_HIGH = 1,
		STD_VIDEO_AV1_PROFILE_PROFESSIONAL = 2,
		STD_VIDEO_AV1_PROFILE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1Level
	{
		STD_VIDEO_AV1_LEVEL_2_0 = 0,
		STD_VIDEO_AV1_LEVEL_2_1 = 1,
		STD_VIDEO_AV1_LEVEL_2_2 = 2,
		STD_VIDEO_AV1_LEVEL_2_3 = 3,
		STD_VIDEO_AV1_LEVEL_3_0 = 4,
		STD_VIDEO_AV1_LEVEL_3_1 = 5,
		STD_VIDEO_AV1_LEVEL_3_2 = 6,
		STD_VIDEO_AV1_LEVEL_3_3 = 7,
		STD_VIDEO_AV1_LEVEL_4_0 = 8,
		STD_VIDEO_AV1_LEVEL_4_1 = 9,
		STD_VIDEO_AV1_LEVEL_4_2 = 10,
		STD_VIDEO_AV1_LEVEL_4_3 = 11,
		STD_VIDEO_AV1_LEVEL_5_0 = 12,
		STD_VIDEO_AV1_LEVEL_5_1 = 13,
		STD_VIDEO_AV1_LEVEL_5_2 = 14,
		STD_VIDEO_AV1_LEVEL_5_3 = 15,
		STD_VIDEO_AV1_LEVEL_6_0 = 16,
		STD_VIDEO_AV1_LEVEL_6_1 = 17,
		STD_VIDEO_AV1_LEVEL_6_2 = 18,
		STD_VIDEO_AV1_LEVEL_6_3 = 19,
		STD_VIDEO_AV1_LEVEL_7_0 = 20,
		STD_VIDEO_AV1_LEVEL_7_1 = 21,
		STD_VIDEO_AV1_LEVEL_7_2 = 22,
		STD_VIDEO_AV1_LEVEL_7_3 = 23,
		STD_VIDEO_AV1_LEVEL_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1FrameType
	{
		STD_VIDEO_AV1_FRAME_TYPE_KEY = 0,
		STD_VIDEO_AV1_FRAME_TYPE_INTER = 1,
		STD_VIDEO_AV1_FRAME_TYPE_INTRA_ONLY = 2,
		STD_VIDEO_AV1_FRAME_TYPE_SWITCH = 3,
		STD_VIDEO_AV1_FRAME_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1ReferenceName
	{
		STD_VIDEO_AV1_REFERENCE_NAME_INTRA_FRAME = 0,
		STD_VIDEO_AV1_REFERENCE_NAME_LAST_FRAME = 1,
		STD_VIDEO_AV1_REFERENCE_NAME_LAST2_FRAME = 2,
		STD_VIDEO_AV1_REFERENCE_NAME_LAST3_FRAME = 3,
		STD_VIDEO_AV1_REFERENCE_NAME_GOLDEN_FRAME = 4,
		STD_VIDEO_AV1_REFERENCE_NAME_BWDREF_FRAME = 5,
		STD_VIDEO_AV1_REFERENCE_NAME_ALTREF2_FRAME = 6,
		STD_VIDEO_AV1_REFERENCE_NAME_ALTREF_FRAME = 7,
		STD_VIDEO_AV1_REFERENCE_NAME_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1InterpolationFilter
	{
		STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP = 0,
		STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP_SMOOTH = 1,
		STD_VIDEO_AV1_INTERPOLATION_FILTER_EIGHTTAP_SHARP = 2,
		STD_VIDEO_AV1_INTERPOLATION_FILTER_BILINEAR = 3,
		STD_VIDEO_AV1_INTERPOLATION_FILTER_SWITCHABLE = 4,
		STD_VIDEO_AV1_INTERPOLATION_FILTER_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1TxMode
	{
		STD_VIDEO_AV1_TX_MODE_ONLY_4X4 = 0,
		STD_VIDEO_AV1_TX_MODE_LARGEST = 1,
		STD_VIDEO_AV1_TX_MODE_SELECT = 2,
		STD_VIDEO_AV1_TX_MODE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1FrameRestorationType
	{
		STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_NONE = 0,
		STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_WIENER = 1,
		STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_SGRPROJ = 2,
		STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_SWITCHABLE = 3,
		STD_VIDEO_AV1_FRAME_RESTORATION_TYPE_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1ColorPrimaries
	{
		STD_VIDEO_AV1_COLOR_PRIMARIES_BT_709 = 1,
		STD_VIDEO_AV1_COLOR_PRIMARIES_UNSPECIFIED = 2,
		STD_VIDEO_AV1_COLOR_PRIMARIES_BT_470_M = 4,
		STD_VIDEO_AV1_COLOR_PRIMARIES_BT_470_B_G = 5,
		STD_VIDEO_AV1_COLOR_PRIMARIES_BT_601 = 6,
		STD_VIDEO_AV1_COLOR_PRIMARIES_SMPTE_240 = 7,
		STD_VIDEO_AV1_COLOR_PRIMARIES_GENERIC_FILM = 8,
		STD_VIDEO_AV1_COLOR_PRIMARIES_BT_2020 = 9,
		STD_VIDEO_AV1_COLOR_PRIMARIES_XYZ = 10,
		STD_VIDEO_AV1_COLOR_PRIMARIES_SMPTE_431 = 11,
		STD_VIDEO_AV1_COLOR_PRIMARIES_SMPTE_432 = 12,
		STD_VIDEO_AV1_COLOR_PRIMARIES_EBU_3213 = 22,
		STD_VIDEO_AV1_COLOR_PRIMARIES_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1TransferCharacteristics
	{
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_RESERVED_0 = 0,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_709 = 1,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_RESERVED_3 = 3,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_470_M = 4,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_470_B_G = 5,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_601 = 6,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_SMPTE_240 = 7,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_LINEAR = 8,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_LOG_100 = 9,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_LOG_100_SQRT10 = 10,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_IEC_61966 = 11,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_1361 = 12,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_SRGB = 13,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_2020_10_BIT = 14,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_BT_2020_12_BIT = 15,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_SMPTE_2084 = 16,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_SMPTE_428 = 17,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_HLG = 18,
		STD_VIDEO_AV1_TRANSFER_CHARACTERISTICS_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1MatrixCoefficients
	{
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_IDENTITY = 0,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_709 = 1,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_UNSPECIFIED = 2,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_RESERVED_3 = 3,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_FCC = 4,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_470_B_G = 5,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_601 = 6,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_240 = 7,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_YCGCO = 8,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_2020_NCL = 9,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_BT_2020_CL = 10,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_SMPTE_2085 = 11,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_CHROMAT_NCL = 12,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_CHROMAT_CL = 13,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_ICTCP = 14,
		STD_VIDEO_AV1_MATRIX_COEFFICIENTS_INVALID = 0x7FFFFFFF,
	}

	public enum StdVideoAV1ChromaSamplePosition
	{
		STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_UNKNOWN = 0,
		STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_VERTICAL = 1,
		STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_COLOCATED = 2,
		STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_RESERVED = 3,
		STD_VIDEO_AV1_CHROMA_SAMPLE_POSITION_INVALID = 0x7FFFFFFF,
	}

}
